"""v2.0: Redesign database model

Revision ID: 2c0d43e0ccc0
Revises: 038e88ae105e
Create Date: 2025-07-13 00:35:11.478181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0d43e0ccc0'
down_revision = '038e88ae105e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('achievements')
    op.drop_table('investments')
    op.drop_table('user_achievements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_assets', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_assets')

    op.create_table('user_achievements',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('achievement_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('investments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year_month', sa.VARCHAR(length=7), nullable=False),
    sa.Column('income', sa.INTEGER(), nullable=False),
    sa.Column('saving', sa.INTEGER(), nullable=False),
    sa.Column('self_investment', sa.INTEGER(), nullable=False),
    sa.Column('financial_investment', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('achievements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('transactions')
    # ### end Alembic commands ###
